config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passengers
    accepts_nested_attributes_for :passengers
    #belongs_to :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :from_airport, class_name: "Airport"
    belongs_to :to_airport, class_name: "Airport"
    has_many :bookings
    has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :bookings
    has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :sanitize_params
    def new
        @flight = Flight.find(@flight_id)
        @passenger = Passenger.new
        @booking = @flight.bookings.new
        @passengers.times { @booking.passengers.build }
    end

    def create
        @passenger = Passenger.new(passenger_params)
        @flight = Flight.find(params[:booking][:flight_id])
        @booking = @flight.bookings.new(booking_params)
        if @passenger.save
            @booking = @passenger.bookings.build(booking_params)
            PassengerMailer.thanks_email(@passenger).deliver_now!
            if @booking.save
                flash[:success] = "Booking saved"
                redirect_to @booking
            end
        end
    end

    def show
        @booking_id = params[:id]
        @booking = Booking.find(@booking_id)
        @passengers = Passenger.where("booking_id = ?", @booking_id)
        @flight_id = Booking.find(@booking_id).flight_id
        @flight = Flight.find(@flight_id)
    end

    private

        def sanitize_params
            @flight_id = params[:id].to_i
            @passengers = params[:num_passengers].to_i
        end

        def booking_params
            params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
        end

        def passenger_params
            params.require(:booking).permit(passenger: [:name, :email])
        end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    before_action :sanitize_params

    def index
        @airport_options = Airport.all.map{ |a| [a.airport_code, a.id] } #loading everytime, scope this or something so it loads once, maybe its the render
        @days = Flight.all.map{ |f| f.start_datetime }
        @flights = Flight.where("from_airport_id = ? AND to_airport_id = ?", @departure, @arrival).map{ |f| f.id }
        #render "flights/index"
    end


    private

        def sanitize_params
            @departure = params[:from_airport].to_i
            @arrival = params[:to_airport].to_i
            #@date = params[:date] ## need to figure out how to use datetime in search
            @passengers = params[:passenger_count].to_i
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Your Booking:</h1>
<br>

Flight ID: <%= @flight.id %>
<br>
Departure: <%= @flight.start_datetime %> from <%= @flight.from_airport.airport_code %>
<br>
Arrival: <%= @flight.end_datetime %> at <%= @flight.to_airport.airport_code %>

<h1>Passengers:</h1>
<p>Please fill out the following information for each passenger in this booking.</p>


<%= form_with model: @booking, url: bookings_path, local: true do |f| %>
	<%= f.fields_for :passengers do |passenger_form| %>
		Passenger<br>
		<%= passenger_form.label :name %>
		<%= passenger_form.text_field :name, placeholder: 'Name' %><br>

		<%= passenger_form.label :email %>
		<%= passenger_form.text_field :email, placeholder: 'Email' %><br>
	<% end %>

	<%= f.hidden_field :flight_id, value: @flight.id %>
	<%= f.submit 'Submit' %>
<% end %>

app/views/bookings/show.html.erb
<h3>Thank you for booking! Here is your confirmation for your records:</h3>

<p>Booking number: <%= @booking.id %></p>
<h4>Flight Info:</h4>
<p>Departing from <%= @flight.to_airport.airport_code %> on <%= @flight.start_datetime %></p> <%# law of demeter violation? %>
<p>Arriving at <%= @flight.from_airport.airport_code %> on <%= @flight.end_datetime %></p>
<p>Total flight time is <%= @flight.flight_duration %></p>
<p><% @passengers.each do |p| %>
    Passenger Name: <%= p.name %>
    <br>
    Passenger Email: <%= p.email %>
    <br>
    <br>
<% end %>
</p>

app/views/flights/index.html.erb
<%= form_with url: flights_path, local: true, method: "get" do %>
    Select your origin city:
    <%= select_tag(:from_airport, options_for_select(@airport_options)) %>
    <br>
    Select your destination:
    <%= select_tag(:to_airport, options_for_select(@airport_options)) %>
    <br>
    Number of passengers:
    <%= select_tag(:passenger_count, options_for_select((1..4))) %>
    <br>
    Departure date:
    <%= select_tag(:date, options_for_select(@days)) %>
    <br>
    <%= submit_tag "Search" %>
<% end %>


<% if @flights.any? %>
Open Flights:
    <%= form_with url: new_booking_path, local: true, method: "get" do %>
        <% @flights.each do |f| %>
            <%= radio_button_tag(:id, "#{f}") %>
            <%= label_tag(:flight_id, "Flight #{f}") %>
            <br>
        <% end %>
        <%= hidden_field_tag :num_passengers, @passengers %> <%#dont need to sanitize to i then pass here because it becomes string again anyways%>
        <%= submit_tag "Choose" %>
    <% end %>
<% else %>
    Sorry, no flights match your search.
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>